[package]
name = "raylang-rust"
version = "0.3.0"
authors = ["Tim Chagnon <tachagnon@gmail.com>"]

[lib]
name = "raylangrust"
crate-type = ["dylib"]

[dependencies]
image = "0.13"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.7"
libc = "0.2"
time = "0.1"
